// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// INTERPBILIN
arma::vec INTERPBILIN(arma::vec& hlGrade, arma::vec& potGrade, arma::mat& rendGrade, arma::vec& hlPred, arma::vec& potPred);
RcppExport SEXP _curvacolina_INTERPBILIN(SEXP hlGradeSEXP, SEXP potGradeSEXP, SEXP rendGradeSEXP, SEXP hlPredSEXP, SEXP potPredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type hlGrade(hlGradeSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type potGrade(potGradeSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type rendGrade(rendGradeSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type hlPred(hlPredSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type potPred(potPredSEXP);
    rcpp_result_gen = Rcpp::wrap(INTERPBILIN(hlGrade, potGrade, rendGrade, hlPred, potPred));
    return rcpp_result_gen;
END_RCPP
}
// PTINPOLY
arma::uvec PTINPOLY(arma::mat& points, arma::mat& poly);
RcppExport SEXP _curvacolina_PTINPOLY(SEXP pointsSEXP, SEXP polySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type poly(polySEXP);
    rcpp_result_gen = Rcpp::wrap(PTINPOLY(points, poly));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_curvacolina_INTERPBILIN", (DL_FUNC) &_curvacolina_INTERPBILIN, 5},
    {"_curvacolina_PTINPOLY", (DL_FUNC) &_curvacolina_PTINPOLY, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_curvacolina(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
