# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolacao Bilinear
#' 
#' Realiza interpolacao bilinear em uma grade tridimensional de valores. Funcao interna
#' 
#' Os argumentos \code{hlGrade} e \code{potGrade} devem corresponder as coordenadas de queda e 
#' potencia contidas na grade em ordem crescente. \code{rendGrade} deve ser uma matrix M x N
#' com o formato
#' 
#' |      | pot_1 | pot_2 |  ... | pot_N |
#' | ---- | ----- | ----- | ---- | ----- | 
#' | hl_1 | rend_11 | rend_12 | ... | rend_1N |
#' | hl_2 | rend_21 | rend_22 | ... | rend_2N |
#' | ...  | ...     | ...     | ... | ...     |
#' | hl_M | rend_M1 | rend_M2 | ... | rend_MN |
#' 
#' \code{hlPred} e \code{potPred} devem ser informados como vetores numericos indicando as 
#' coordenadas onde interpolar. Os pontos devem ser fornecidos ordenados por \code{potPred} em
#' ordem crescente. Isto e necessario para que se possa usar uma pesquisa mais otimizada na matriz
#' de rendimentos e, assim, tornar a funcao mais eficiente
#' 
#' @param hlGrade,potGrade,rendGrade valores das variaveis explicativas (x e y) e dependente (z), na grade
#' @param hlPred,potPred valores das variaveis explicativas a interpolar na grade
#' 
#' @return vetor de valores interpolados
INTERPBILIN <- function(hlGrade, potGrade, rendGrade, hlPred, potPred) {
    .Call(`_curvacolina_INTERPBILIN`, hlGrade, potGrade, rendGrade, hlPred, potPred)
}

#' Implementacao Do Algoritmo Raycasting
#' 
#' Identifica quais observacoes em \code{pontos} estao dentro do poligono \code{poly}
#' 
#' Esta funcao assume que linhas de \code{poly} representam vertices adjacentes. Nao importa onde
#' o primeiro vertice esta, contanto que cada nova linha indique o proximo vertice do poligono em
#' um mesmo sentido de deslocamento. Sera considerado que o primeiro vertice e o adjacente ao 
#' ultimo no sentido de deslocamento.
#' 
#' @param points matriz contendo as coordenadas dos pontos a testar
#' @param poly matriz contendo as coordenadas dos vertices do poligono. Ver Detalhes
#' 
#' @return vetor coluna de 0s e 1s indicando quais pontos estao dentro do poligono
PTINPOLY <- function(points, poly) {
    .Call(`_curvacolina_PTINPOLY`, points, poly)
}

